eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${vcap.services.routing-eureka-service.credentials.uri}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: 0
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
